[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.20" }
fulladle = { id = "com.osacky.fulladle", version = "0.17.4" }
kotlin = { id = "kotlin" }
java-library = { id = "java-library" }
kapt = { id = "org.jetbrains.kotlin.kapt" }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = "kotlin" }
kotlin-parcelize = { id = 'org.jetbrains.kotlin.plugin.parcelize', version.ref = 'kotlin' }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.12.0" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.24-1.0.20" }
spotless = { id = "com.diffplug.spotless", version = "6.1.2" }

[versions]

agp = "8.5.2"
androidx-databinding = "8.5.1"
androidx-legacy = "1.0.0"
anvil = "2.5.0-beta11"
coroutines = "1.7.3"
kotlin = "1.9.24"
moshi = "1.8.0"
okhttp = "4.12.0"
retrofit = "2.9.0"

[libraries]

androidx-appCompat = "androidx.appcompat:appcompat:1.6.1"
androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-recyclerView = "androidx.recyclerview:recyclerview:1.3.2"
androidx-swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-webkit = "androidx.webkit:webkit:1.11.0"

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

leakCanary = 'com.squareup.leakcanary:leakcanary-android:2.10'

material = "com.google.android.material:material:1.7.0"

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-adapter-rxJava2 = { module="com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

## Do not update RxJava versions
rxJava2 = "io.reactivex.rxjava2:rxjava:2.2.9"
rxJava2-android = "io.reactivex.rxjava2:rxandroid:2.0.2"

timber = "com.jakewharton.timber:timber:5.0.1"

dokka-analysis = "org.jetbrains.dokka:dokka-analysis:1.8.20"

dokka-base = "org.jetbrains.dokka:dokka-base:1.8.20"

gfm-template-processing-plugin = "org.jetbrains.dokka:gfm-template-processing-plugin:1.8.20"

all-modules-page-plugin = "org.jetbrains.dokka:all-modules-page-plugin:1.8.20"

jekyll-template-processing-plugin = "org.jetbrains.dokka:jekyll-template-processing-plugin:1.8.20"

flank = "com.github.flank:flank:21.+"

kotlin-scripting-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }

android-device-provider-ddmlib = "com.android.tools.utp:android-device-provider-ddmlib:31.6.0-rc01"

android-device-provider-gradle = "com.android.tools.utp:android-device-provider-gradle:31.6.0-rc01"

android-driver-instrumentation = "com.google.testing.platform:android-driver-instrumentation:0.0.9-alpha02"

android-test-plugin = "com.google.testing.platform:android-test-plugin:0.0.9-alpha02"

android-test-plugin-host-additional-test-output = "com.android.tools.utp:android-test-plugin-host-additional-test-output:31.6.0-rc01"

android-test-plugin-host-apk-installer = "com.android.tools.utp:android-test-plugin-host-apk-installer:31.6.0-rc01"

android-test-plugin-host-coverage = "com.android.tools.utp:android-test-plugin-host-coverage:31.6.0-rc01"

android-test-plugin-host-device-info = "com.android.tools.utp:android-test-plugin-host-device-info:31.6.0-rc01"

android-test-plugin-host-emulator-control = "com.android.tools.utp:android-test-plugin-host-emulator-control:31.6.0-rc01"

android-test-plugin-host-logcat = "com.android.tools.utp:android-test-plugin-host-logcat:31.6.0-rc01"

android-test-plugin-host-retention = "com.android.tools.utp:android-test-plugin-host-retention:31.6.0-rc01"

android-test-plugin-result-listener-gradle = "com.android.tools.utp:android-test-plugin-result-listener-gradle:31.6.0-rc01"

com-google-testing-platform-core = "com.google.testing.platform:core:0.0.9-alpha02"

launcher = "com.google.testing.platform:launcher:0.0.9-alpha02"

viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "androidx-databinding" }

annotations = { group = "com.squareup.anvil", name = "annotations", version.ref = "anvil" }

mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.3.1"

com-squareup-anvil-compiler = { group = "com.squareup.anvil", name = "compiler", version.ref = "anvil" }

symbol-processing = "com.google.devtools.ksp:symbol-processing:1.9.24-1.0.20"

symbol-processing-api = "com.google.devtools.ksp:symbol-processing-api:1.9.24-1.0.20"

symbol-processing-cmdline = "com.google.devtools.ksp:symbol-processing-cmdline:1.9.24-1.0.20"

compiler-api = { group = "com.squareup.anvil", name = "compiler-api", version.ref = "anvil" }

compiler-utils = { group = "com.squareup.anvil", name = "compiler-utils", version.ref = "anvil" }

auto-service-annotations = "com.google.auto.service:auto-service-annotations:1.1.0"

auto-service-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.1.0"

ksp = "com.github.bumptech.glide:ksp:4.14.2"

legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "androidx-legacy" }

konfetti = "nl.dionsegijn:konfetti:1.2.5"

glide = "com.github.bumptech.glide:glide:4.14.2"

okhttp3-integration = "com.github.bumptech.glide:okhttp3-integration:4.14.2"

lottie = "com.airbnb.android:lottie:5.2.0"

jsoup = "org.jsoup:jsoup:1.15.3"

flipper = "com.facebook.flipper:flipper:0.176.1"

soloader = "com.facebook.soloader:soloader:0.10.5"

kotlin-annotation-processing-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-annotation-processing-gradle", version.ref = "kotlin" }

kotlin-parcelize-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-parcelize-runtime", version.ref = "kotlin" }

kotlin-parcelize-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-parcelize-compiler", version.ref = "kotlin" }

android-database-sqlcipher = "net.zetetic:android-database-sqlcipher:4.5.1"

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

harmony = "com.frybits.harmony:harmony:1.2.2"

harmony-crypto = "com.frybits.harmony:harmony-crypto:1.2.6"

javax-annotation = "org.glassfish:javax.annotation:10.0-b28"

commons-math3 = "org.apache.commons:commons-math3:3.6.1"

relinker = "com.getkeepsafe.relinker:relinker:1.4.5"

lint-api = "com.android.tools.lint:lint-api:31.6.0-rc01"

lint-checks = "com.android.tools.lint:lint-checks:31.6.0-rc01"

lint-tests = "com.android.tools.lint:lint-tests:31.6.0-rc01"

conscrypt-openjdk-uber = "org.conscrypt:conscrypt-openjdk-uber:2.5.0"

shimmer = "com.facebook.shimmer:shimmer:0.5.0"

conscrypt-android = "org.conscrypt:conscrypt-android:2.5.0"

zxing-android-embedded = "com.journeyapps:zxing-android-embedded:4.3.0"

com-google-zxing-core = "com.google.zxing:core:3.3.0"

json = "org.json:json:20230227"

sync-crypto-android = "com.duckduckgo.synccrypto:sync-crypto-android:0.3.0"

netguard-android = "com.duckduckgo.netguard:netguard-android:1.6.12"
