name: Autofill Feature Critical Path End-to-End tests

on:
  schedule:
    - cron: '30 6 * * *' # run at 6.30 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation_tests:
    runs-on: ubuntu-latest
    name: Autofill Critical Path End-to-End Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create folder
        if: always()
        run: mkdir apk

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble APK which does not require auth to use Autofill
        run: ./gradlew assemblePlayRelease -Pautofill-disable-auth-requirement -Pforce-default-variant -x lint

      - name: Move APK to new folder
        if: always()
        run: find . -name "*.apk"  -exec mv '{}' apk/release.apk \;

      - name: Autofill Critical Path E2E Flows
        uses: mobile-dev-inc/action-maestro-cloud@v1.8.1
        with:
          api-key: ${{ secrets.MOBILE_DEV_API_KEY }}
          name: ${{ github.sha }}
          app-file: apk/release.apk
          android-api-level: 34
          workspace: .maestro
          include-tags: autofillNoAuthTests