name: Sync Feature Critical Path End-to-End tests

on:
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation_tests:
    runs-on: ubuntu-latest
    name: Sync Feature Critical Path End-to-End tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create test account for Sync and return the recovery code
        uses: duckduckgo/sync_crypto/action@main
        id: sync-recovery-code
        with:
          debug: true
          no-teardown: false # Turn this to true so the account is not deleted after the test

      - id: maestro
        name: Run Sync flows
        uses: mobile-dev-inc/action-maestro-cloud@v1.8.1
        with:
          api-key: ${{ secrets.MOBILE_DEV_API_KEY }}
          name: ${{ github.sha }}
          app-binary-id: 6d7b908045f1ffe798b5d006debce00d40d6f43d
          android-api-level: 30
          workspace: .maestro/sync_flows
          include-tags: syncCriticalPathTest
          env: |
            CODE=${{ steps.sync-recovery-code.outputs.recovery-code }}

      - name: Maestro Output
        run: |
          echo "Console URL: ${{ steps.maestro.outputs.MAESTRO_CLOUD_CONSOLE_URL }}"
          echo "Flow Results: ${{ steps.maestro.outputs.MAESTRO_CLOUD_FLOW_RESULTS }}"
          echo "Upload Status: ${{ steps.maestro.outputs.MAESTRO_CLOUD_UPLOAD_STATUS }}"
          echo "App Binary ID:: ${{ steps.maestro.outputs.MAESTRO_CLOUD_APP_BINARY_ID }}"
