name: Sync Feature Critical Path End-to-End tests

on:
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation_tests:
    runs-on: ubuntu-latest
    name: Sync Feature Critical Path End-to-End tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create test account for Sync and return the recovery code
        uses: duckduckgo/sync_crypto/action@main
        id: sync-recovery-code
        with:
          debug: true
          no-teardown: false # Turn this to true so the account is not deleted after the test

      - name: Create folder
        if: always()
        run: mkdir apk

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Assemble internal release APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleInternalRelease -Pforce-default-variant -x lint

      - name: Move APK to new folder
        if: always()
        run: find . -name "*.apk"  -exec mv '{}' apk/release.apk \;

      - name: Sync Flows
        uses: mobile-dev-inc/action-maestro-cloud@v1.8.1
        with:
          api-key: ${{ secrets.MOBILE_DEV_API_KEY }}
          name: ${{ github.sha }}
          app-file: apk/release.apk
          android-api-level: 30
          workspace: .maestro
          include-tags: syncCriticalPathTest
          env: |
            CODE=${{ steps.sync-recovery-code.outputs.recovery-code }}